name: imagekit
description: Imagekit package for uploading
version: 0.0.5
repository: https://github.com/nstack-in/imagekit.git
homepage: https://www.nstack.in/

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  http: ^1.2.2
